* Jumble - llmII's collection of Janet utilities
For some reason I believe others may find these useful. Rather than having
these hide in other things I write as non-exported definitions, the things
that inspire that belief will find their place here.

** Installation:
One can install this with ~jpm install https://github.com/llmII/jumble~

** Use:
We'll strive to have a decent doc string for things where we can so just use
the REPL and Janet's ~doc~ function. When such seems insufficient, or
something warrants a deeper explanation, we'll place such near the end of the
README.

The main thing however, is ~(import jumble)~ and use ~jumble/*~. That or you
could ~(use jumble)~ where living with the prefix ~jumble~ seems like too much
noise for you.

* Submodules

** ~jumble/aliasing~
When you import ~jumble~ these should be available under ~jumble/*~ and are
utilities for creating aliases to a symbol such that when you have a symbol
~sym~ you can create aliases like ~sym-alias~ that will share all properties
that ~sym~ has (meaning the doc string for both will be the same), with there
being an option to have one property that is differing from the original
~sym~, being whether or not the new alias ~sym-alias~ is exported.

** ~jumble/moddoc~
Utilities for modifying the doc strings of dyns.

** Future: ~jumble/defun~

* NOTES:
README.md is generated from the README.org file, so there may be instances
where the README.org is more up to date, though we'll try to avoid that.

** TODO Create tests

** TODO Fix jumble-redef to expose a better interface
Right now it has a few definitions for redef with export as true or not. Need
to do this in a better way.
